services:
  maintenance:
    container_name: maintenance
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/maintenance
    networks:
      - default
    tty: true
    secrets:
      - id_rsa
volumes:
  maintenance:
secrets:
  id_rsa:
    file: ${SSH_KEY}
